Navigation
igorkol91/AwesomeBooks pull request #5
Opened 2021-08-12 14:16 UTC by Munsa1

In this milestone we added:
- luxon logic for adding the current time on the page
- added a navbar with 3 clickable elements (booklist, create new, about us)
- "book list" is displaying all the books added to the local storage
- "create new" contains the form for adding new books
- "about us" contains the contact information

2021-08-12 15:36 UTC, mimipeshy requested changes
## Hi @Munsa1 and @igorkol91 👋🏾 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a PR description. Kindly add a brief summary of what you achieved in the description box.
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2021-08-12 17:06 UTC, Lameck1 requested changes
Hi @igorkol91 & @Munsa1 👋🏼, 

Good job so far! You've come a long way with this project and your good effort is recognizable.

In this last milestone, we would like to ship a good product if not a perfect one. For this reason, there are suggestions that we need to look into just before we could move ahead. See below 👇🏼:


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-12 17:06 UTC, Lameck1 commented on style.css
> +}
- [x] The CSS file does not have enough style to match up with the minimum style requirement as in the provided wireframe. We are given Wireframes to be guiding principles as to how the UI should result. So, we've not done justice here as far as this issue is concerned. [Please watch this video recording in which I address this issue.](https://www.loom.com/share/54bca187b89249ad9029c347f0a6f275). </br> Finally, a screenshot of the wireframes 👇🏼. Please let our pages look at least like what we are seeing below.

| The Wireframes |
| --- |
| ![wireframe](https://user-images.githubusercontent.com/45002654/129233970-4c11407f-e1e3-4d1e-8a98-219c3ff3db89.png) |

2021-08-12 17:06 UTC, Lameck1 commented on index.html
> +    </div>
- [x] [OPTIONAL] I suggest using more semantic HTML tags to communicate the real intentions of a given section of an HTML document. Take a look at [THIS](https://www.w3schools.com/html/html5_semantic_elements.asp) to learn more about semantic HTML. Contents required in this section are included though 👍🏼.

2021-08-12 17:06 UTC, Lameck1 commented on index.html
>  </body>
- [x] We have forgotten the footer here. The wireframe requires this of us. Please let's work on it.

2021-08-12 17:06 UTC, Lameck1 commented on main.js
> +};
- [x] This is the problem that makes your page not load books when the page is loaded for the first time or when refreshed. The second call to `window.load` overrides/overshadows the first. I suggest you have one instance of `window.load` and do everything else you wanted with `window.load`. Somethign like this 👇🏼:

```JavaScript
window.onload = () => {
  refreshDOM();
  time.innerHTML = `${ now.c.month } ${ now.c.day } ${ now.c.year }, ${ now.c.hour }:${ now.c.minute }:${ now.c.second }`;
};
```

2021-08-13 07:58 UTC, DeliceLydia commented on style.css
> +}
Addressed this well!

2021-08-13 07:59 UTC, DeliceLydia commented on index.html
>  </body>
Well addressed this

2021-08-13 07:59 UTC, DeliceLydia commented on main.js
> +};
resolved it!

2021-08-13 08:00 UTC, DeliceLydia approved these changes
# Congratulations🎉 🎉 

## Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard).. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-13 08:02 UTC, merged